hackacities/urls.py
from django.conf.urls import patterns, url, include
from hackacities import views

urlpatterns = patterns('',

    # Hackacity management
    url(r'^view/(?P<hc>.+)/$', views.view_hackacity, name='view_hackacity'),

    # Hackacity management
    url(r'^edit/(?P<hc>.+)/$', views.edit_hackacity, name='edit_hackacity'),
)

hackaglobal/urls.py
from django.conf.urls import patterns, url, include
from hackaglobal import views, ajax

urlpatterns = patterns('',

    #FrontEnd
    url(r'^$', views.home, name='home'),
    url(r'^web/(?P<country>.+)/$', views.getCountryListView, name='country_list_view'),


    #Backend
    url(r'^find/$', views.find_events, name='find_events'),
    url(r'^create/$', views.add_event, name='add_event'),
    url(r'^manage/$', views.manage_events, name='manage_all'),
    url(r'^delete/(?P<event_id>.+)/$', views.delete_event, name='delete_event'),
    url(r'^manage/(?P<event_id>.+)/$', views.edit_event, name='edit_event'),
    url(r'^event/(?P<event_id>.+)/$', views.view_event, name='manage_event'),


    # Handling all AJAX calls
    url(r'^attend_event/$', ajax.attend_event, name='attend_event'),
    url(r'^add_container/$', ajax.add_container, name='add_container'),
    url(r'^remove_container/$', ajax.remove_container, name='remove_container'),
    url(r'^add_team/$', ajax.add_team, name='add_team'),
    url(r'^remove_team/$', ajax.remove_team, name='remove_team'),
)

urls.py
from django.conf.urls import patterns, url, include
from settings import STATIC_ROOT, MEDIA_ROOT

from django.contrib import admin
admin.autodiscover()


handler500 = 'djangotoolbox.errorviews.server_error'
handler404 = 'hackaglobal.views.handler404'

urlpatterns = patterns('',

    #My Apps
    url(r'^api/', include('apihg.urls')),
    url(r'accounts/', include('accounts.urls')),
    url(r'hackacity/', include('hackacities.urls')),
    url(r'', include('hackaglobal.urls')),


    #External Apps
    url(r'', include('social_auth.urls')),


    #Admin
    ('^admin/', include(admin.site.urls)),


    #Static files
    (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': STATIC_ROOT}),
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': MEDIA_ROOT}),

)

hackacities/models.py
from django.db import models

from django.contrib.auth.models import User
from hackaglobal.tools.toolbox import  path_and_rename
from django.utils.translation import ugettext as _


CONTAINER_TYPE_CHOICES = (
        ('S1', 'Gold Sponsor'),
        ('S2', 'Silver Sponsor'),
        ('S3', 'Bronze Sponsor'),
        ('P1', 'Partner'),
        ('P2', 'Media Partner'),
    )

class HackaContainer(models.Model):
    title = models.CharField(max_length=50)
    description = models.CharField(max_length=200)
    photo = models.ImageField(upload_to=path_and_rename('hackacities/sponsors/', u'sponsor'))
    url = models.URLField()
    hackacity = models.ForeignKey("HackaCity", null=True, blank=True)

    type = models.CharField(max_length=2, choices=CONTAINER_TYPE_CHOICES, default='S1')

    def __unicode__(self):
        return self.title + ": " + self.type + " - " + self.hackacity.name

class HackaCity(models.Model):
    lead = models.ForeignKey(User, related_name="lead_of")
    team = models.ManyToManyField(User, related_name="team_of", null=True, blank=True)
    member = models.ManyToManyField(User, related_name="member_of", null=True, blank=True)

    image_logo = models.ImageField(upload_to=path_and_rename('hackacities/logos/', u'logo'))
    image_home = models.ImageField(upload_to=path_and_rename('hackacities/home/', u'home'), null=True, blank=True)
    image_about = models.ImageField(upload_to=path_and_rename('hackacities/about/', u'about'), null=True, blank=True)
    image_divider_1 = models.ImageField(upload_to=path_and_rename('hackacities/dividers/', u'divider'), null=True, blank=True)
    image_divider_2 = models.ImageField(upload_to=('hackacities/dividers/', u'divider'), null=True, blank=True)
    image_divider_3 = models.ImageField(upload_to=path_and_rename('hackacities/dividers/', u'divider'), null=True, blank=True)
    image_divider_4 = models.ImageField(upload_to=path_and_rename('hackacities/dividers/', u'divider'), null=True, blank=True)

    name = models.CharField(max_length=25)
    short_description = models.CharField(max_length=200)
    about = models.TextField()
    city = models.OneToOneField('Cities')

#    sponsors = models.ForeignKey(HackaContainer, related_name="sponsor_of", null=True, blank=True)
#    communities = models.ForeignKey(HackaContainer, related_name="community_of", null=True, blank=True)
#    partners = models.ForeignKey(HackaContainer, related_name="partner_of", null=True, blank=True)

    def image_tag(self): return u'<img src="%s" />' % (self.photo.url if self.photo else '/static/home/img/full_logo.png')
    image_tag.short_description = 'Image'
    image_tag.allow_tags = True

    def get_hacka(self): return self.name.replace("Hacka","")

    def get_image_home(self): return self.image_home.url if self.image_home else '/static/defaultmedia/default-hackacity-home.jpg'
    def get_image_about(self): return self.image_about.url if self.image_about else '/static/defaultmedia/default-hackacity-about.png'
    def get_image_divider_1(self): return self.image_divider_1.url if self.image_divider_1 else '/static/defaultmedia/default-hackacity-divider-1.png'
    def get_image_divider_2(self): return self.image_divider_2.url if self.image_divider_2 else '/static/defaultmedia/default-hackacity-divider-2.jpg'
    def get_image_divider_3(self): return self.image_divider_3.url if self.image_divider_3 else '/static/defaultmedia/default-hackacity-divider-3.png'
    def get_image_divider_4(self): return self.image_divider_4.url if self.image_divider_4 else '/static/defaultmedia/default-hackacity-divider-4.jpg'

    def __unicode__(self):
        return self.city.name

class Cities(models.Model):
    name = models.CharField(max_length=35L)
    country = models.ForeignKey('Countries')

    def __unicode__(self):
        return self.name

class Countries(models.Model):
    code = models.CharField(max_length=3L, primary_key=True)
    name = models.CharField(max_length=52L)
    continent = models.CharField(max_length=13L)

    def __unicode__(self):
        return self.name

#
#class Cities(models.Model):
#    id = models.IntegerField(primary_key=True)
#    name = models.CharField(max_length=35L)
#    country_code = models.CharField(max_length=3L)
#    district = models.CharField(max_length=20L)
#    population = models.IntegerField()
#    country = models.ForeignKey('Countries')
#
#    def __unicode__(self):
#        return self.name
#
#class Countries(models.Model):
#    code = models.CharField(max_length=3L, primary_key=True)
#    name = models.CharField(max_length=52L)
#    continent = models.CharField(max_length=13L)
#    region = models.CharField(max_length=26L)
#    surface_area = models.FloatField()
#    independence_year = models.IntegerField(null=True, blank=True)
#    population = models.IntegerField()
#    life_expectancy = models.FloatField(null=True, blank=True)
#    gnp = models.FloatField(null=True, blank=True)
#    gnp_old = models.FloatField(null=True, blank=True)
#    local_name = models.CharField(max_length=45L)
#    government_form = models.CharField(max_length=45L)
#    head_of_state = models.CharField(max_length=60L, blank=True)
#    capital = models.IntegerField(null=True, blank=True)
#    code2 = models.CharField(max_length=2L)
#
#    def __unicode__(self):
#        return self.name
#
#class Languages(models.Model):
#    country = models.ForeignKey('Countries')
#    country_code = models.CharField(max_length=3)
#    language = models.CharField(max_length=30)
#    official = models.CharField(max_length=1)
#    percentage = models.FloatField()
#
#    def __unicode__(self):
#        return self.language

hackacities/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse
from django.shortcuts import redirect
from django.http import HttpResponseRedirect

from hackaglobal.tools.forms import HackaCityCreationForm

from hackacities.models import HackaCity
from hackaglobal.models import Event

from django.db.models import Q

import settings


def view_hackacity(request, hc):

    print hc

    if hc.lower() == "global":
        return HttpResponseRedirect(reverse('home'))

    try:
        print "here"
        hackacity = HackaCity.objects.get(name=hc)
        upcoming_events = Event.objects.filter(hackacity=hackacity).order_by('-start')

    except HackaCity.DoesNotExist:
        try:
            if hc.isdigit():
                hackacity = HackaCity.objects.get(pk=hc)
                print hackacity.name
            else:
                hackacity = HackaCity.objects.get(Q(city__name=hc) | Q(name="Hacka"+hc))

            return HttpResponseRedirect(reverse('view_hackacity', args=[hackacity.name]))

        except HackaCity.DoesNotExist:
            return render(request, 'generic_message.html', { 'header' : 'HackaCity not found', 'message': "Oops, we couldn't the HackaCity you were looking for..." })

    try:
        is_hackateam = HackaCity.objects.filter(id=hackacity.pk, team=request.user).exists()
    except:
        is_hackateam = False

    return render(request, 'hackacity/hackacity_view.html', { 'hackacity': hackacity, 'is_hackateam':is_hackateam, 'upcoming_events': upcoming_events })


def edit_hackacity(request, hc):

    data = {}
    data['form'] = request.POST.get("form", "")

    try:
        if hc.isdigit():
            data['hackacity'] = HackaCity.objects.get(pk=hc, team=request.user)
        else:
            data['hackacity'] = HackaCity.objects.get(Q(name=hc) | Q(city__name=hc), team=request.user)

    except:
        return render(request, 'generic_message.html', { 'header' : 'HackaCity not found', 'message': "Oops, we couldn't the HackaCity you were looking for..." })


    try:

        if request.method =='POST':
            data['form'] = HackaCityCreationForm(request.POST, request.FILES)

            # Check if form is valid and if the user is part of the event hackacity's team
            if data['form'].is_valid():
                new_hackacity = data['form'].save(commit=False)
                new_hackacity.id = data['hackacity'].id
                new_hackacity.name = data['hackacity'].name
                new_hackacity.city = data['hackacity'].city
                new_hackacity.lead = data['hackacity'].lead

                if not new_hackacity.image_logo: new_hackacity.image_logo = data['hackacity'].image_logo
                if not new_hackacity.image_about: new_hackacity.image_about = data['hackacity'].image_about
                if not new_hackacity.image_home: new_hackacity.image_home = data['hackacity'].image_home
                if not new_hackacity.image_divider_1: new_hackacity.image_divider_1 = data['hackacity'].image_divider_1
                if not new_hackacity.image_divider_2: new_hackacity.image_divider_2 = data['hackacity'].image_divider_2
                if not new_hackacity.image_divider_3: new_hackacity.image_divider_3 = data['hackacity'].image_divider_3
                if not new_hackacity.image_divider_4: new_hackacity.image_divider_4 = data['hackacity'].image_divider_4

                new_hackacity.save()

                data['hackacity'] = new_hackacity
        else:
            data['form'] = HackaCityCreationForm()

    except Exception, err:
        # Event not found so raise an event not found
        return render(request, 'generic_message.html', { 'header' : 'Event not found...', 'message': err if settings.DEBUG else "Oops, we couldn't find the event you were looking for..." })


    data['is_lead'] = data['hackacity'].lead == request.user

    return render(request, 'hackacity/hackacity_edit.html', data)

templates/hackacity/hackacity_view.html
{% extends "base.html" %}

{% block head-includes %}
    <link rel="stylesheet" type="text/css" href="/static/css/hackacity_view.css">
    <link rel="stylesheet" type="text/css" href="/static/css/events_container.css">
    <script type="text/javascript" src="/static/js/hackacity_view.js"></script>
{% endblock %}

{% block content %}
{% load hg_tags %}
<style>
    .hackacity-view-home{ background: url({{ hackacity.get_image_home }}) 50% 0 no-repeat fixed; background-size: cover; }
    .hackacity-view-about{ background: url({{ hackacity.get_image_about }}) 50% 0 no-repeat fixed; background-size: cover; }
    .hackacity-view-divider-1{ background: url({{ hackacity.get_image_divider_1 }}) 50% 0 no-repeat fixed; background-size: cover; }
    .hackacity-view-divider-2{ background: url({{ hackacity.get_image_divider_2 }}) 50% 0 no-repeat fixed; background-size: cover; }
    .hackacity-view-divider-3{ background: url({{ hackacity.get_image_divider_3 }}) 50% 0 no-repeat fixed; background-size: cover; }
    .hackacity-view-divider-4{ background: url({{ hackacity.get_image_divider_4 }}) 50% 0 no-repeat fixed; background-size: cover; }
</style>
<div id="home">
    <section class="hackacity-view-home hackacity-section">
        <div class="hackacity-view-home-gradient">

            <img class="hackacity-view-home-hackalogo" src="{{ hackacity.image_logo.url }}">

            <h1 class="hackacity-view-home-text">
                {{ hackacity.short_description }}
            </h1>
        </div>
    </section>
    <section id="about" class="hackacity-view-about hackacity-section">
        <div class="hackacity-view-title">{ About }</div>
        <div class="hackacity-view-about-text col-md-offset-1 col-md-5">
            {% autoescape off %} {{ hackacity.about }} {% endautoescape %}
        </div>
        <div class="col-sm-offset-2 col-sm-8 col-md-offset-0 col-md-5">
            <div class="col-md flex-video hackacity-view-about-video">
                <iframe src="http://www.youtube.com/embed/z0J_AQXZcG4" frameborder="0"></iframe>
            </div>
        </div>
    </section>
    <section class="hackacity-view-divider hackacity-view-divider-1">

    </section>
    <section id="events" class="hackacity-view-events hackacity-section" style="background-image: url(https://s.evbuc.com/https_proxy?url=http%3A%2F%2Fblog.ecollegefinder.org%2Fwp-content%2Fuploads%2F2012%2F01%2F101474454.jpg&sig=ADR2i78zbIVBa8kaMzYeLJetMCGfzGrzwg)">
        <div class="hackacity-view-title hackacity-view-title-event" style="color: black" title="{ Events }">
            { Events }
        </div>
        <div class="hackacity-view-events-list" style="margin-top: -40px">
            <ul class="list-inline hackacity-view-events-list-inline">
                {% for event in upcoming_events %}
                    {% include 'layouts/hackacity_event.html' %}
                {% endfor %}
            </ul>
        </div>
    </section>
{#    <section class="hackacity-view-divider hackacity-view-divider-2">#}
{##}
{#    </section>#}
{#    <section id="communities" class="hackacity-view-communities hackacity-section" style="background: url(/static/img/hackacommunities.png) 50% 0 no-repeat fixed; background-size: cover">#}

    </section>
    <section class="hackacity-view-divider-3" style="position: relative; height:480px; padding: 50px 50px 50px 50px; overflow: hidden">
        <div class="well col-md-offset-1 col-md-10" style="height:380px; padding: 50px 50px 50px 50px; overflow: scroll">
            <script async src="https://d36hc0p18k1aoc.cloudfront.net/public/js/modules/tintembed.js"></script>
            <div class="tintup" data-id="hackaglobal" data-columns="4" data-expand="true" style="height:380px;width:100%; margin: auto auto; overflow: hidden;">
                <a href="http://www.tintup.com" style="width:118px;height:31px;background-image:url(//d33w9bm0n1egwm.cloudfront.net/assets/logos/poweredbytintsmall.png);position:absolute;bottom:10px;right: 20px;text-indent: -9999px;z-index:9;">hashtag campaign</a>
            </div>
        </div>
    </section>
    <section id="sponsors" class="hackacity-view-sponsors hackacity-section">
        <div class="hackacity-view-title" style="padding-top: 140px; color: black">
            { Sponsors }
        </div>
        {% get_hackacontainers hackacity "S1" as s1_sponsors %}
        {% get_hackacontainers hackacity "S2" as s2_sponsors %}
        {% get_hackacontainers hackacity "S3" as s3_sponsors %}
        {% if s1_sponsors %}
            {% include 'layouts/hackacity_view_hackacontainer.html' with container_name="Golden Sponsors" container_type="S1" hackacontainers=s1_sponsors %}
        {% endif %}
        {% if s2_sponsors %}
            {% include 'layouts/hackacity_view_hackacontainer.html' with container_name="Silver Sponsors" container_type="S2" hackacontainers=s2_sponsors %}
        {% endif %}
        {% if s3_sponsors %}
            {% include 'layouts/hackacity_view_hackacontainer.html' with container_name="Bronze Sponsors" container_type="S3" hackacontainers=s3_sponsors %}
        {% endif %}
        {% if not hackacity.hackacontainer_set.all %}
            <a href="mailito:{{ hackacity.name }}@gmail.com"  class="btn btn-default"><h1>Become the first sponsor of {{ hackacity.name }}! </h1> </a>
        {% endif %}
    </section>
    <section class="hackacity-view-divider hackacity-view-divider-4">

    </section>
{#    <section id="partners" class="hackacity-view-partners hackacity-section" style="background: url(/static/img/partners.png) 50% 0 no-repeat fixed;">#}
{##}
{#    </section>#}
    <section id="team" class="hackacity-view-team" style="overflow-y: hidden; position: relative; background-color: white;">
        <div class="content">
            <div class="wrapper">
                <div class="block" id="theteam">
                    <div class="hackacity-view-title" style="color: black; width: 100%; text-align: center">
                        { Team }
                    </div>
                    <div class="people-wrapper">
                        <ul class="people">
                            {% include 'layouts/team_member.html' with team_member=hackacity.lead.profile lead=True  %}
                            {% for u in hackacity.team.all %}
                                {% if u != hackacity.lead  %}
                                    {% include 'layouts/team_member.html' with team_member=u.profile lead=False  %}
                                {% endif %}
                            {% endfor %}
                        </ul>
                        <div class="clear"></div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="hackacity-view-contact hackacity-view-divider" style="position: relative; background: url(/static/img/contact.png); background-position: fixed; width: 100%; ">
        <div class="hackacity-view-title" style="padding-top: 140px">
            { Contact }
        </div>
        <a href="mailito:{{ hackacity.name }}@gmail.com"><h1 style="color: orange">{{ hackacity.name }}@gmail.com</h1></a>
    </section>
</div>
{% endblock %}